jobs:
  build:
    machine:
      image: ubuntu-2204:2022.04.2

    steps:
      - checkout

      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t node-hello-world:$TAG .
          
      - run: docker images list 

      - run: |
          echo 'Donwloading most recent Sysdig CLI scanner'
          curl -LO "https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/$(curl -L -s https://download.sysdig.com/scanning/sysdig-cli-scanner/latest_version.txt)/linux/amd64/sysdig-cli-scanner"
          chmod +x ./sysdig-cli-scanner
      - run: echo 'DOCKER_HOST: $DOCKER_HOST'
      - run: ./sysdig-cli-scanner --console-log --apiurl $SYSDIG_SECURE_API docker://node-hello-world:$TAG
